export const FETCH_ANIME_LIST_START = 'FETCH_ANIME_LIST_START';
export const FETCH_ANIME_LIST_SUCCESS = 'FETCH_ANIME_LIST_SUCCESS';
export const FETCH_ANIME_LIST_FAIL = 'FETCH_ANIME_LIST_FAIL';

export const FETCH_ANIME_CAT_START = 'FETCH_ANIME_CAT_START';
export const FETCH_ANIME_CAT_SUCCESS = 'FETCH_ANIME_CAT_SUCCESS';
export const FETCH_ANIME_CAT_FAIL = 'FETCH_ANIME_CAT_FAIL';
